vich_uploader:
    db_driver: orm

    mappings:
        presta_image:
            uri_prefix: /uploads/images/prestations
            upload_destination: '%kernel.project_dir%/public/uploads/images/prestations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        conseil_members:
            uri_prefix: /uploads/images/conseil_members
            upload_destination: '%kernel.project_dir%/public/uploads/images/conseil_members'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
